### ISSUE TITLE
UCLA: Frederic William Taylor Papers, 1897-1944 [#28366]

### ISSUE THREAD

**Issue by gamontoya** [ucldc/harvest-ops#261]
## Collection details
- Collection Registry URL: https://registry.cdlib.org/admin/library_collection/collection/28366
- Endpoint: 
- Preview on -stage: https://calisphere-stage.cdlib.org/collections/28366
- Published on -prod: https://calisphere.org/collections/28366

## Communications
- Freshdesk thread URL: https://help.oac.cdlib.org/a/tickets/154824

## Request type
[Select all that apply]
- [x] New collection harvest
- [ ] Re-harvest whole collection (on request)
- [ ] Re-harvest metadata only (on request)
- [ ] Scheduled recurring harvests
- [ ] Delete whole collection (remove from publication)
- [ ] Item record removals (remove from publication)
- [ ] OAC METS replacement
- [ ] Redirects needed
- [ ] Other

Notes:

## Harvesting request details
11/20/2024 15:53:43
Share a *new* collection on Calisphere
UCLA
Molly Haigh
Another DAMS or digital collection platform
UCLA: Frederic William Taylor Papers, 1897-1944 [#28366]
Correspondence, clippings, photographs, certificates, awards, letters of citation and related printed material concerning the activities of Taylor as Director General of El Salvador Agriculture and developer of rubber in the United States. Also included are 14 scrapbooks, reports, etc. with manuscripts and memorabilia kept by Taylor as Superintendent of Horticulture and Director of Concessions at the Buffalo Exposition, 1901. This is arranged under such headings as: annals, McKinley assassination, horticulture, concessions reports, foods and their accessories, and reports of the agricultural and horticultural division.
https://digital.library.ucla.edu/catalog/ark:/21198/zz00093kt1
http://www.oac.cdlib.org/findaid/ark:/13030/ft8199n8z7
mhaigh@library.ucla.edu
tksangwand@library.ucla.edu
https://help.oac.cdlib.org/a/tickets/154824

**Comment by aturner** [comment]
UCLA approved 12/11; published that day
