### ISSUE TITLE
UCR: Trailfinders collection [#22838]

### ISSUE THREAD

**Issue by gamontoya** [ucldc/harvest-ops#301]
## Collection details
- Collection Registry URL: 
- Endpoint: 
- Preview on -stage: 

## Communications
- Freshdesk thread URL: https://help.oac.cdlib.org/a/tickets/142286

## Request type
[Select all that apply]
- [ ] New collection harvest
- [x] Re-harvest whole collection (on request)
- [ ] Re-harvest metadata only (on request)
- [ ] Scheduled recurring harvests
- [ ] Delete whole collection (remove from publication)
- [ ] Item record removals (remove from publication)
- [ ] OAC METS replacement
- [ ] Redirects needed
- [ ] Other

Notes:

## Harvesting request details
8/15/2024 8:45:20
Update or add items to an *existing* collection on Calisphere
University of California, Riverside
Krystal Boehlert
Nuxeo (UC campuses)
22838
/asset-library/UCR/SCUA/Archival/MS353/published
New content + metadata added to collections, Boxes 16-25, 30 have been added
krystal.boehlert@ucr.edu
A) Relation B) Series C) alphanumerically so that the Series appear in order
natalie.moller@ucr.edu

**Comment by aturner** [comment]
@gamontoya do you mind checking in the logs for the total number of content/media files that were fetched for this collection, and relaying the number to Natalie at UCR? 

There's currently no easy way to directly verify the total number of files for a given collection / project folder in Nuxeo; the fetch log info will be helpful for them to determine the size, until we are able to more easily generate extent stats reports.

**Comment by gamontoya** [comment]
@aturner This is what the log says:

- `[2024-08-23, 16:00:32 UTC] {{logging_mixin.py:150}} INFO - 235 parent items 16 parent pages 6942 child items 242 child pages`
- `[2024-08-23, 16:00:32 UTC] {{logging_mixin.py:150}} INFO - 22838 : success,   258 pages,   7177 items,     73 solr items,   162 new items, solr count last updated: May 02, 2023 15:26:52.772121`

What part do you want me to send to Natalie?
