### ISSUE TITLE
UCSF Library: Marion Baldur Sulzberger papers [#28012]

### ISSUE THREAD

**Issue by christinklez** [ucldc/harvest-ops#323]
## Collection details
- Collection Registry URL: https://registry.cdlib.org/admin/library_collection/collection/28012/change/
- Endpoint: Nuxeo
- Preview on -stage: https://calisphere-stage.cdlib.org/collections/28012/ 

## Communications
- Freshdesk thread URL
  - https://help.oac.cdlib.org/a/tickets/118590 
  - https://help.oac.cdlib.org/a/tickets/119705

## Request type
[Select all that apply]
- [x] New collection harvest
- [ ] Re-harvest whole collection (on request)
- [ ] Re-harvest metadata only (on request)
- [ ] Scheduled recurring harvests
- [ ] Delete whole collection (remove from publication)
- [ ] Item record removals (remove from publication)
- [ ] OAC METS replacement
- [ ] Redirects needed
- [ ] Other

Notes:

## Harvesting request details
[copy/paste from webform request]

**Comment by gamontoya** [comment]
Notified Lisa N. on 2024-08-12 (https://help.oac.cdlib.org/a/tickets/118590)

**Comment by gamontoya** [comment]
On Hold, per Lisa N.

**Comment by gamontoya** [comment]
@christinklez This is closeable, but I don't have permissions to `close` tickets.

**Comment by christinklez** [comment]
@gamontoya - thank you! I just updated permissions for the `harvest_ops` repository & this project board. Can you check if you're able to close this issue, whenever you have a moment? Thank you!

**Comment by gamontoya** [comment]
@christinklez Yup, works now! Thank you.

**Comment by christinklez** [comment]
This actually didn't make it to production https://calisphere.org/collections/28012/

I'm seeing in Airflow that there was an error in the publication task. I tried re-running it, and continue to hit that same error. I also tried reharvesting the collection, and also getting an error.

I'll look into this in a bit.

**Comment by gamontoya** [comment]
@christinklez I see this in production, so can you explain the issue with this collection?

**Comment by christinklez** [comment]
@gamontoya I actually just published this yesterday and forgot to update this card.

Here's the Airflow task with that publish_collection error: 
https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/publish_collection/grid?num_runs=365&base_date=2024-09-04T18%3A21%3A57Z&dag_run_id=manual__2024-08-21T17%3A52%3A18%2B00%3A00&task_id=get_version_pages

And here's the error message in the log:
```
Traceback (most recent call last):
  File "/usr/local/airflow/dags/rikolti/utils/storage.py", line 76, in list_pages
    return list_s3_pages(data, recursive=recursive, **kwargs)
  File "/usr/local/airflow/dags/rikolti/utils/storage.py", line 110, in list_s3_pages
    keys += [f"s3://{data.bucket}/{obj['Key']}" for obj in obj_list['Contents']]
KeyError: 'Contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/shared_tasks/indexing_tasks.py", line 111, in get_version_pages
    version_pages = get_with_content_urls_pages(version)
  File "/usr/local/airflow/dags/rikolti/utils/versions.py", line 174, in get_with_content_urls_pages
    page_list = storage.list_pages(data_path, recursive=True, **kwargs)
  File "/usr/local/airflow/dags/rikolti/utils/storage.py", line 86, in list_pages
    raise FileNotFoundError
FileNotFoundError
```

I went ahead and re-harvested from scratch, and then published the collection through yesterday. Thanks!
